feat: create handle error page
ignasiusadhitia/final-project-front pull request #16
Opened 2024-12-20 12:27 UTC by dvpms

handler for error request http.
Preview:
![image](https://github.com/user-attachments/assets/91802b92-69a7-4bab-b5d4-10d73aa6c9e7)
![image](https://github.com/user-attachments/assets/2979b531-59ff-409e-b0c2-2465e0f31f55)
![image](https://github.com/user-attachments/assets/6756a647-9908-4093-9e29-47074f70fe56)

2024-12-20 12:59 UTC, ignasiusadhitia requested changes
warna button dan border-radius mohon disesuaikan dengan design

2024-12-20 12:59 UTC, ignasiusadhitia commented on src/pages/Error.jsx
> +        className="bg-red-500 hover:bg-red-700 text-white font-bold py-3 px-6 rounded-lg transition duration-300"
```suggestion
        className="bg-button-2 hover:bg-button-hover-1 text-text-1 font-medium py-3 px-6 rounded transition duration-300"
```

2024-12-20 13:54 UTC, ignasiusadhitia commented on src/hooks/errorHandler.js
begini ternyata @dvpms @desup1421 @rikkriuk  setelah dicari tahu lebih jauh:

Kode tersebut adalah **custom hook** berdasarkan karakteristiknya. Berikut adalah alasannya:

---

### **Karakteristik Custom Hook yang Terpenuhi:**

1. **Dimulai dengan "use"**:
   - Nama `useErrorHandler` mengikuti konvensi penamaan custom hook di React, yang harus dimulai dengan "use".

2. **Menggunakan Hook Lain di Dalamnya**:
   - Hook bawaan React Router, yaitu `useNavigate`, digunakan di dalam `useErrorHandler`. Ini adalah salah satu syarat utama custom hook, yaitu menggabungkan atau memperluas logika hooks bawaan.

3. **Mematuhi Rules of Hooks**:
   - `useNavigate` dipanggil di tingkat atas fungsi, bukan dalam kondisi, loop, atau fungsi bersarang.
   - Karena dipanggil di dalam `useErrorHandler`, maka `useErrorHandler` juga harus digunakan dalam konteks React (misalnya, di dalam komponen atau custom hook lain).

4. **Mengabstraksi Logika yang Dapat Digunakan Ulang**:
   - Fungsi `handleError` di dalam `useErrorHandler` adalah logika reusable untuk menangani error berdasarkan status HTTP dan melakukan navigasi yang relevan. Ini adalah pola yang umum dalam custom hooks untuk mengisolasi logika dari komponen.

---

### **Perbedaan dengan Fungsi Biasa**

Jika kode ini adalah fungsi biasa, maka:
1. **Tidak Menggunakan Hook**:
   - Fungsi biasa tidak dapat memanggil `useNavigate` karena itu adalah hook React yang hanya dapat digunakan dalam komponen atau custom hook.

2. **Tidak Dipanggil di Komponen atau Custom Hook**:
   - Fungsi biasa bisa dipanggil di mana saja tanpa aturan khusus, tetapi `useErrorHandler` memanfaatkan hook yang memerlukan konteks React.

3. **Contoh Fungsi Error Handler Biasa**:
   Jika Anda ingin kode ini menjadi fungsi error handler biasa, Anda harus menghapus dependensi pada `useNavigate` dan menggantinya dengan sesuatu yang lebih global, seperti `window.location`:
   ```javascript
   export const handleError = (error) => {
     const status = error?.response?.status;
     
     switch (status) {
       case 401:
         window.location.href = '/401';
         break;
       case 403:
         window.location.href = '/401';
         break;
       case 404:
         window.location.href = '/404';
         break;
       case 500:
         window.location.href = '/500';
         break;
       default:
         window.location.href = '/404';
     }
   };
   ```

---

### **Kesimpulan**
Kode Anda adalah **custom hook** karena:
- Menggunakan `useNavigate` (hook bawaan React Router).
- Mengikuti aturan hooks di React.
- Dapat digunakan kembali oleh komponen React lain.

Jika Anda tidak memerlukan integrasi dengan hooks React seperti `useNavigate`, maka Anda dapat mengubahnya menjadi fungsi biasa. Namun, jika ingin menjaga konteks React Router untuk navigasi, mempertahankannya sebagai custom hook adalah pilihan yang tepat.

2024-12-21 08:23 UTC, dvpms commented on src/hooks/errorHandler.js
mantap. penempatan file berarti sudah sesuai ya.

2024-12-21 08:25 UTC, ignasiusadhitia commented on src/hooks/errorHandler.js
ya, sudah sesuai, well done @dvpms

2024-12-21 08:32 UTC, ignasiusadhitia approved these changes

2024-12-21 08:33 UTC, ignasiusadhitia commented
well done 🚀 🚀 🚀 @dvpms

2024-12-21 08:33 UTC, merged